insert into public.site_content (
  page, section_key, section_label, title, body, image_url, button_text, button_url, layout, sort_order, published
) values
  ('freight-dispatch-masterclass', 'hero', 'FREIGHT DISPATCH MASTERCLASS', 'Become a Freight Dispatcher', 'The Freight Dispatch Masterclass is a step-by-step training designed to teach you how to become a professional freight dispatcher from scratch. Explore the program overview here, then continue to our dedicated masterclass website when you’re ready to enroll.', '', 'Enroll now', '', 'text', 1, true),
  ('freight-dispatch-masterclass', 'benefits', 'WHY DISPATCH TRAINING', 'Why Dispatch Training is the Best Choice', 'Build earning potential, pursue your goals, improve your quality of life, and work with greater location freedom.', '', '', '', 'text', 2, true),
  ('freight-dispatch-masterclass', 'curriculum', 'WHAT YOU’LL LEARN', 'Your Step-by-Step Training Guide', 'Learn freight dispatch fundamentals, carrier relationships, rate negotiation, paperwork, compliance, professional communication, and how to manage multiple trucks.', '', '', '', 'text', 3, true),
  ('freight-broker-masterclass', 'hero', 'FREIGHT BROKER MASTERCLASS', 'Build the skills to connect freight with opportunity.', 'A step-by-step introduction to freight brokerage for aspiring professionals ready to understand the industry, develop practical skills, and build a clear path forward.', '', 'Visit Masterclass Website', 'https://imanfreightbroker.com/', 'text', 1, true),
  ('freight-broker-masterclass', 'foundation', 'YOUR BROKERAGE FOUNDATION', 'Learn the business from every angle.', 'Build a working understanding of the people, processes, and decisions behind successful freight movement.', '', '', '', 'text', 2, true),
  ('freight-broker-masterclass', 'curriculum', 'WHAT YOU’LL LEARN', 'A practical roadmap for freight brokerage.', 'Review the program here, then continue to the dedicated masterclass website for enrollment details and full access.', '', '', '', 'text', 3, true),
  ('iman-trucking-school', 'hero', 'IMAN TRUCKING SCHOOL', 'Your road to a trucking career starts here.', 'Explore a clear path toward the trucking and logistics industry through focused education, practical preparation, and guidance built around your future.', '', 'Visit School Website', 'https://iman-trucking-school-website.netlify.app/', 'text', 1, true),
  ('iman-trucking-school', 'training', 'TRAIN FOR THE ROAD AHEAD', 'Build a strong professional foundation.', 'Our overview introduces the areas that matter when preparing for a responsible, opportunity-driven career in trucking.', '', '', '', 'text', 2, true),
  ('iman-trucking-school', 'journey', 'YOUR NEXT MILESTONE', 'A simple path from interest to action.', 'Start with this overview, then continue to the dedicated school website for the latest program and enrollment information.', '', '', '', 'text', 3, true),
  ('consultants', 'hero', 'PERSONALIZED GUIDANCE', 'Schedule a Consultation with Our Experts', 'Get practical, personalized guidance for your freight brokerage, trucking, dispatch, or CDL training goals. Choose your service and reserve a time in minutes.', '', 'Book Consultation', '#booking', 'text', 1, true),
  ('tracking', 'hero', 'SHIPMENT VISIBILITY', 'Know where your shipment stands.', 'Enter your Iman tracking or load number to view the latest status, route progress, estimated delivery, and shipment milestones.', '', 'Track shipment', '#tracking-form', 'text', 1, true),
  ('car-auto-sales', 'hero', 'IMAN CAR & TRUCK SALES', 'Find the right car or truck for your next move', 'Explore our approach to car and commercial truck sales, then continue to our dedicated sales website to browse inventory and make an inquiry.', '', 'Visit sales website', 'https://tiny-kringle-175161.netlify.app/', 'text', 1, true),
  ('car-auto-sales', 'buying-process', 'BUY WITH CONFIDENCE', 'A simpler way to buy', 'Personal guidance at every stage of your vehicle search.', '', '', '', 'text', 2, true),
  ('careers', 'hero', 'BUILD YOUR CAREER WITH US', 'Move freight. Build what’s next.', 'Join a logistics team committed to safe transportation, dependable service, and meaningful opportunities for people ready to grow.', '', 'View open positions', '#open-positions', 'text', 1, true),
  ('careers', 'positions', 'OPEN POSITIONS', 'Find your next opportunity', 'Explore current roles for drivers, dispatchers, coordinators, and support professionals.', '', '', '', 'text', 2, true),
  ('about-us', 'hero', 'ABOUT IMAN LOGISTICS', 'Practical knowledge. Professional confidence. Real direction.', 'Iman Logistics empowers aspiring logistics professionals with clear, step-by-step education and the confidence to take meaningful action.', '', 'Schedule a consultation', '/consultants/', 'text', 1, true),
  ('about-us', 'story', 'OUR STORY', 'A clearer pathway into logistics', 'We simplify the process, remove unnecessary confusion, and provide tools that can be applied with confidence.', '', '', '', 'text', 2, true),
  ('contact-us', 'hero', 'LET’S START A CONVERSATION', 'Questions deserve clear answers.', 'Contact Iman Logistics for training information, consultation guidance, or help choosing your next step in freight and trucking.', '', 'Send a message', '#contact-form', 'text', 1, true),
  ('contact-us', 'form', 'TELL US HOW WE CAN HELP', 'Send a detailed message', 'Required fields help us understand your request and respond through your preferred method.', '', '', '', 'text', 2, true)
on conflict (page, section_key) do nothing;
